# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathPack@5
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'UiPath novauspoc'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'
- task: UiPathTest@5
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'UiPath novauspoc'
    folderName: 'Demos\Testing'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'